name: courseverse_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_transition: '^2.0.9'
  font_awesome_flutter: '>= 4.7.0'
  google_sign_in: ^6.1.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  get: ^4.6.5
  cloud_firestore: ^4.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  assets:
    - images/


  uses-material-design: true

